### PR TITLE
generic-const-param-types design doc

### PR DESCRIPTION
**Pull request by lcnr**
cc @nikomatsakis @varkor

### CODE REVIEW

**Comment by jplatte** [comment]
I was about to ask about the "reverse" (trait bounds depending on const parameters), I see that this already works, even by mentioning a const param that's declared *after* (tested that because of the ordering restriction on stable):

```rust
trait X<const N: usize> {}
fn foo<T: X<N>, const N: usize>() {}
```

Is it intentional that that compiles?

**Comment by lcnr** [comment]
yeah, trait bounds are fine. Is there a reason you expect those to be a problem?

**Comment by jplatte** [comment]
Sorry for the noise. I was previously under the impression that one could only refer to a generic parameter in other parameters that come after it, but it seems like this is not the case for type of lifetime parameters either.

```rust
fn bar<T: PartialEq<U>, U>() {}
fn baz<'a: 'b, 'b>() {}
```

**Comment by lcnr** [comment]
yeah, type bounds are fine, this restriction exists for type defaults which is probably what you are thinking of.
 `struct Foo<T = U, U = i32>(T, U)`

**Pull request merged**
